# Generated by Django 2.2.3 on 2019-07-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiegand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name_text',
            new_name='group_text',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='name_text',
            new_name='reader_text',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name_text',
            new_name='tag_text',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name_text',
            new_name='user_text',
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_text',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
