# Generated by Django 2.2.3 on 2019-07-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiegand', '0002_auto_20190723_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='state_text',
            field=models.CharField(choices=[('A', 'On'), ('P', 'Off'), ('L', 'Lock')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reader',
            name='model_text',
            field=models.CharField(choices=[('T', 'Tag reader'), ('P', 'PinPad'), ('K', 'KeyPad'), ('N', 'NFC antenna')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reader',
            name='state_text',
            field=models.CharField(choices=[('A', 'On'), ('P', 'Off'), ('L', 'Lock'), ('B', 'Busy')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='state_text',
            field=models.CharField(choices=[('A', 'On'), ('P', 'Off'), ('L', 'Lock')], max_length=1),
        ),
    ]
