# Generated by Django 2.2.3 on 2019-08-06 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiegand', '0006_auto_20190731_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='associated_pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiegand.Pin'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='associated_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiegand.Tag'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='status_trigger_value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
